# Damn Vulnerable NodeJS Application

version: "2.1"
services:
  app:
    image: llalondedkhub/log8100-dvna:latest
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - postgres-db
    env_file:
      - ./vars.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  postgres-db:
    image: postgres:16.4
    restart: always
    expose:
      - "5432"
    env_file:
      - ./vars.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
     - ./watchtower.env
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LABEL_ENABLE=true

volumes:
  postgres_data: