# Damn Vulnerable NodeJS Application

version: "2.1"
services:
  app:
    image: llalondedkhub/log8100-dvna:latest
    ports:
      - 9090:9090
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    env_file:
      - ./vars.env

  postgres-db:
    image: postgres:16.4
    expose:
      - "5432"
    env_file:
      - ./vars.env