# Damn Vulnerable NodeJS Application

version: "2.1"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 9090:9090
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    env_file:
      - ./vars.env

  postgres-db:
    image: postgres:16.4
    restart: always
    expose:
      - "5432"
    env_file:
      - ./vars.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: