name: Production Release Workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  tag-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Version from Branch Name
      id: extract_version
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        if [[ "$BRANCH_NAME" =~ ^release/(.*)$ ]]; then
          VERSION=${BASH_REMATCH[1]}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "Not a release branch. Exiting."
          exit 1
        fi

    - name: Create Git Tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
        git push origin "v${{ env.VERSION }}"

    - name: Rename Docker Image Tag
      run: |
        docker pull ${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_REPOSITORY }}:staging-${{ env.VERSION }}
        docker tag ${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_REPOSITORY }}:staging-${{ env.VERSION }} ${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.VERSION }}
        docker push ${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.VERSION }}