on:
  push:
    branches:
      - 'release/**'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Dynamic Application Security Testing (DAST)
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: ${{ secrets.WEB_APP_DNS }}
