on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: master
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: ${{ secrets.WEB_APP_DNS }}
