on:
  push:
    branches:
      - master
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: ${{ secrets.WEB_APP_DNS }}
